export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const TOGGLE_CREATE_MODAL = "TOGGLE_CREATE_MODAL";
export const TOGGLE_UPDATE_MODAL = "TOGGLE_UPDATE_MODAL";
export const TOGGLE_CONFIRMATION_MODAL = "TOGGLE_CONFIRMATION_MODAL";
export const SET_ATHLETES = "SET_ATHLETES";
export const SET_SELECTED_ATHLETE = "SET_SELECTED_ATHLETE";
export const SET_SPORTS = "SET_SPORTS";